version: '3.8'

services:
  web:
    build: 
      context: ./blogicum
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER: devops_practice
      - POSTGRES_PASSWORD: 123
      - POSTGRES_DB: devops_practice
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  default:
    driver: bridge
    