name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Сборка и запуск Docker-контейнера
        run: docker-compose up -d --build

      - name: Проверка статуса контейнера
        run: docker-compose ps

      - name: Тестирование приложения
        run: |
          docker-compose exec -T web python manage.py test
